name: climate_diagrams
description: A Flutter web app for displaying climate diagrams

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  fl_chart: ^0.68.0
  intl: ^0.19.0

  cupertino_icons: ^1.0.8
  go_router: ^16.2.4
  fpdart: ^1.1.1
  watch_it: ^1.7.0
  fast_immutable_collections: ^11.0.4
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  safe_change_notifier: ^0.4.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  freezed: ^3.2.3
  build_runner: ^2.8.0
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true